name: Changelog

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    branches:
      - main
    paths:
      - 'src/**'

jobs:
  changelog:
    name: CHANGELOG
    runs-on: ubuntu-latest

    steps:
    - 