
name: Rust

on:
  pull_request:
    branches:
    - main
  push:
    branches:
    - main

jobs:
  build_checks:
    name: ${{ matrix.task.name }} (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    env:
      RUST_BACKTRACE: full
      RUSTC_WRAPPER: sccache
      RUSTV: ${{ matrix.rust }}
      SCCACHE_CACHE_SIZE: 1G
      CACHE_PREFIX: v0
    strategy:
      fail-fast: false
      matrix: