
name: Rust

on:
  pull_request:
    branches:
    - main
  push:
    branches:
    - main

jobs:
  build_checks:
    name: ${{ matrix.task.name }} (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    env:
      RUST_BACKTRACE: full
      RUSTC_WRAPPER: sccache
      RUSTV: ${{ matrix.rust }}
      SCCACHE_CACHE_SIZE: 1G
      CACHE_PREFIX: v0
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        rust: [stable]
        task:
          - name: Test (default-tls)
            run: cargo test --features build-binary,default-tls

          - name: Test (rustls-tls)
            run: cargo test --features build-binary,rustls-tls

        include:
          - os: ubuntu-latest
            rust: stable
            task:
              name: Format
              run: cargo fmt -- --check

          - os: ubuntu-latest
            rust: stable
            task:
              name: Lint
              run: cargo clippy --all-targets --features build-binary -- -D warnings
          
          - os: ubuntu-latest
            rust: stable
            task:
              name: Audit
              run: cargo audit

          - os: ubuntu-latest
            rust: nightly
            task:
              name: Build docs